spring:
  datasource:
    url: jdbc:postgresql://rc1b-ydc8j4z3ajcc3uca.mdb.yandexcloud.net:6432/user-credentials
    username: postgres1
    password: postgres1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  application:
    name: api-auth

server:
  port: 8090

eureka:
  client:
    service-url:
      default-zone: ${EUREKA.URI:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true
