spring:
  datasource:
    url: jdbc:postgresql://rc1b-aba7ujxtchgjaaf5.mdb.yandexcloud.net:6432/user-credentials
    username: postgres1
    password: postgres1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  application:
    name: api-auth

server:
  port: 8090

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://localhost:8761/eureka}
