server:
  port: ${PORT:8761}

spring:
  application:
    name: eureka-server

eureka:
  client:
    registerWithEureka: ${REGISTRY_SERVICE_HA:false}
    fetchRegistry: ${REGISTRY_SERVICE_HA:false}
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_URL:http://localhost:8761/eureka}